// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Artifact struct {
	ID        string    `json:"id"`
	ScanID    string    `json:"scan_id"`
	Type      string    `json:"type"`
	Engine    string    `json:"engine"`
	Format    string    `json:"format"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type EngineRun struct {
	ID            string     `json:"id"`
	ScanID        string     `json:"scan_id"`
	Engine        string     `json:"engine"`
	Category      string     `json:"category"`
	Command       *string    `json:"command"`
	Status        string     `json:"status"`
	ExitCode      *int64     `json:"exit_code"`
	DurationMs    *int64     `json:"duration_ms"`
	RawOutputPath *string    `json:"raw_output_path"`
	ErrorMessage  *string    `json:"error_message"`
	StartedAt     *time.Time `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
}

type Finding struct {
	ID               string    `json:"id"`
	ProjectID        string    `json:"project_id"`
	ScanID           string    `json:"scan_id"`
	EngineRunID      string    `json:"engine_run_id"`
	Engine           string    `json:"engine"`
	Category         string    `json:"category"`
	RuleID           string    `json:"rule_id"`
	Title            string    `json:"title"`
	Description      *string   `json:"description"`
	Severity         string    `json:"severity"`
	CvssScore        *float64  `json:"cvss_score"`
	CvssVector       *string   `json:"cvss_vector"`
	Cwe              *string   `json:"cwe"`
	FilePath         *string   `json:"file_path"`
	StartLine        *int64    `json:"start_line"`
	EndLine          *int64    `json:"end_line"`
	StartCol         *int64    `json:"start_col"`
	EndCol           *int64    `json:"end_col"`
	Snippet          *string   `json:"snippet"`
	PkgName          *string   `json:"pkg_name"`
	InstalledVersion *string   `json:"installed_version"`
	FixedVersion     *string   `json:"fixed_version"`
	SecretType       *string   `json:"secret_type"`
	Url              *string   `json:"url"`
	Host             *string   `json:"host"`
	Port             *string   `json:"port"`
	Method           *string   `json:"method"`
	ReferencesJson   *string   `json:"references_json"`
	UniqueIDFromTool *string   `json:"unique_id_from_tool"`
	HashCode         string    `json:"hash_code"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
}

type Project struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Scan struct {
	ID            string     `json:"id"`
	ProjectID     string     `json:"project_id"`
	Target        string     `json:"target"`
	ScanType      string     `json:"scan_type"`
	Profile       *string    `json:"profile"`
	Status        string     `json:"status"`
	StartedAt     *time.Time `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	TriggerSource string     `json:"trigger_source"`
	CreatedAt     time.Time  `json:"created_at"`
}

type ScanFinding struct {
	ScanID    string `json:"scan_id"`
	FindingID string `json:"finding_id"`
	HashCode  string `json:"hash_code"`
}
