// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const countCommonFindings = `-- name: CountCommonFindings :one
SELECT COUNT(*) FROM scan_findings a
JOIN scan_findings b ON a.hash_code = b.hash_code
WHERE a.scan_id = ?1 AND b.scan_id = ?2
`

type CountCommonFindingsParams struct {
	ScanID   string `json:"scan_id"`
	ScanID_2 string `json:"scan_id_2"`
}

func (q *Queries) CountCommonFindings(ctx context.Context, arg CountCommonFindingsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommonFindings, arg.ScanID, arg.ScanID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFindingsByProject = `-- name: CountFindingsByProject :one

SELECT COUNT(*) FROM findings WHERE project_id = ?
`

// ============================================================================
// stats
// ============================================================================
func (q *Queries) CountFindingsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFindingsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFindingsByScan = `-- name: CountFindingsByScan :one
SELECT COUNT(*) FROM findings WHERE scan_id = ?
`

func (q *Queries) CountFindingsByScan(ctx context.Context, scanID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFindingsByScan, scanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFindingsByScanAssoc = `-- name: CountFindingsByScanAssoc :one
SELECT COUNT(*) FROM scan_findings WHERE scan_id = ?
`

func (q *Queries) CountFindingsByScanAssoc(ctx context.Context, scanID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFindingsByScanAssoc, scanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFindingsBySeverity = `-- name: CountFindingsBySeverity :many
SELECT severity, COUNT(*) AS count
FROM findings
WHERE project_id = ?
GROUP BY severity
`

type CountFindingsBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountFindingsBySeverity(ctx context.Context, projectID string) ([]CountFindingsBySeverityRow, error) {
	rows, err := q.db.QueryContext(ctx, countFindingsBySeverity, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFindingsBySeverityRow
	for rows.Next() {
		var i CountFindingsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsBySeverityByScan = `-- name: CountFindingsBySeverityByScan :many
SELECT severity, COUNT(*) AS count
FROM findings
WHERE scan_id = ?
GROUP BY severity
`

type CountFindingsBySeverityByScanRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountFindingsBySeverityByScan(ctx context.Context, scanID string) ([]CountFindingsBySeverityByScanRow, error) {
	rows, err := q.db.QueryContext(ctx, countFindingsBySeverityByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFindingsBySeverityByScanRow
	for rows.Next() {
		var i CountFindingsBySeverityByScanRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsBySeverityByScanAssoc = `-- name: CountFindingsBySeverityByScanAssoc :many
SELECT f.severity, COUNT(*) AS count
FROM scan_findings sf
JOIN findings f ON f.id = sf.finding_id
WHERE sf.scan_id = ?
GROUP BY f.severity
`

type CountFindingsBySeverityByScanAssocRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountFindingsBySeverityByScanAssoc(ctx context.Context, scanID string) ([]CountFindingsBySeverityByScanAssocRow, error) {
	rows, err := q.db.QueryContext(ctx, countFindingsBySeverityByScanAssoc, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFindingsBySeverityByScanAssocRow
	for rows.Next() {
		var i CountFindingsBySeverityByScanAssocRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFindingsOnlyInScan = `-- name: CountFindingsOnlyInScan :one
SELECT COUNT(*) FROM scan_findings sf
WHERE sf.scan_id = ?1 AND NOT EXISTS (
  SELECT 1 FROM scan_findings other WHERE other.scan_id = ?2 AND other.hash_code = sf.hash_code
)
`

type CountFindingsOnlyInScanParams struct {
	ScanID   string `json:"scan_id"`
	ScanID_2 string `json:"scan_id_2"`
}

func (q *Queries) CountFindingsOnlyInScan(ctx context.Context, arg CountFindingsOnlyInScanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFindingsOnlyInScan, arg.ScanID, arg.ScanID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (id, scan_id, type, engine, format, content)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, scan_id, type, engine, format, content, created_at
`

type CreateArtifactParams struct {
	ID      string `json:"id"`
	ScanID  string `json:"scan_id"`
	Type    string `json:"type"`
	Engine  string `json:"engine"`
	Format  string `json:"format"`
	Content string `json:"content"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.ID,
		arg.ScanID,
		arg.Type,
		arg.Engine,
		arg.Format,
		arg.Content,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Type,
		&i.Engine,
		&i.Format,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createEngineRun = `-- name: CreateEngineRun :one
INSERT INTO engine_runs (
  id, scan_id, engine, category, command, status, exit_code, duration_ms,
  raw_output_path, error_message, started_at, completed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, scan_id, engine, category, command, status, exit_code, duration_ms, raw_output_path, error_message, started_at, completed_at
`

type CreateEngineRunParams struct {
	ID            string     `json:"id"`
	ScanID        string     `json:"scan_id"`
	Engine        string     `json:"engine"`
	Category      string     `json:"category"`
	Command       *string    `json:"command"`
	Status        string     `json:"status"`
	ExitCode      *int64     `json:"exit_code"`
	DurationMs    *int64     `json:"duration_ms"`
	RawOutputPath *string    `json:"raw_output_path"`
	ErrorMessage  *string    `json:"error_message"`
	StartedAt     *time.Time `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
}

func (q *Queries) CreateEngineRun(ctx context.Context, arg CreateEngineRunParams) (EngineRun, error) {
	row := q.db.QueryRowContext(ctx, createEngineRun,
		arg.ID,
		arg.ScanID,
		arg.Engine,
		arg.Category,
		arg.Command,
		arg.Status,
		arg.ExitCode,
		arg.DurationMs,
		arg.RawOutputPath,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i EngineRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Engine,
		&i.Category,
		&i.Command,
		&i.Status,
		&i.ExitCode,
		&i.DurationMs,
		&i.RawOutputPath,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createScan = `-- name: CreateScan :one
INSERT INTO scans (id, project_id, target, scan_type, profile, status, trigger_source)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at
`

type CreateScanParams struct {
	ID            string  `json:"id"`
	ProjectID     string  `json:"project_id"`
	Target        string  `json:"target"`
	ScanType      string  `json:"scan_type"`
	Profile       *string `json:"profile"`
	Status        string  `json:"status"`
	TriggerSource string  `json:"trigger_source"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, createScan,
		arg.ID,
		arg.ProjectID,
		arg.Target,
		arg.ScanType,
		arg.Profile,
		arg.Status,
		arg.TriggerSource,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.ScanType,
		&i.Profile,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerSource,
		&i.CreatedAt,
	)
	return i, err
}

const createScanFinding = `-- name: CreateScanFinding :exec

INSERT INTO scan_findings (scan_id, finding_id, hash_code) VALUES (?, ?, ?)
ON CONFLICT(scan_id, hash_code) DO NOTHING
`

type CreateScanFindingParams struct {
	ScanID    string `json:"scan_id"`
	FindingID string `json:"finding_id"`
	HashCode  string `json:"hash_code"`
}

// ============================================================================
// scan_findings (per-scan association, diff)
// ============================================================================
func (q *Queries) CreateScanFinding(ctx context.Context, arg CreateScanFindingParams) error {
	_, err := q.db.ExecContext(ctx, createScanFinding, arg.ScanID, arg.FindingID, arg.HashCode)
	return err
}

const deleteScan = `-- name: DeleteScan :exec
DELETE FROM scans WHERE id = ?
`

func (q *Queries) DeleteScan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteScan, id)
	return err
}

const getEngineRun = `-- name: GetEngineRun :one

SELECT id, scan_id, engine, category, command, status, exit_code, duration_ms, raw_output_path, error_message, started_at, completed_at FROM engine_runs WHERE id = ?
`

// ============================================================================
// engine_runs
// ============================================================================
func (q *Queries) GetEngineRun(ctx context.Context, id string) (EngineRun, error) {
	row := q.db.QueryRowContext(ctx, getEngineRun, id)
	var i EngineRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Engine,
		&i.Category,
		&i.Command,
		&i.Status,
		&i.ExitCode,
		&i.DurationMs,
		&i.RawOutputPath,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getFinding = `-- name: GetFinding :one

SELECT id, project_id, scan_id, engine_run_id, engine, category, rule_id, title, description, severity, cvss_score, cvss_vector, cwe, file_path, start_line, end_line, start_col, end_col, snippet, pkg_name, installed_version, fixed_version, secret_type, url, host, port, method, references_json, unique_id_from_tool, hash_code, status, created_at FROM findings WHERE id = ?
`

// ============================================================================
// findings
// ============================================================================
func (q *Queries) GetFinding(ctx context.Context, id string) (Finding, error) {
	row := q.db.QueryRowContext(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScanID,
		&i.EngineRunID,
		&i.Engine,
		&i.Category,
		&i.RuleID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwe,
		&i.FilePath,
		&i.StartLine,
		&i.EndLine,
		&i.StartCol,
		&i.EndCol,
		&i.Snippet,
		&i.PkgName,
		&i.InstalledVersion,
		&i.FixedVersion,
		&i.SecretType,
		&i.Url,
		&i.Host,
		&i.Port,
		&i.Method,
		&i.ReferencesJson,
		&i.UniqueIDFromTool,
		&i.HashCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSBOMByScan = `-- name: GetLatestSBOMByScan :one
SELECT id, scan_id, type, engine, format, content, created_at FROM artifacts
WHERE scan_id = ? AND type = 'sbom'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSBOMByScan(ctx context.Context, scanID string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getLatestSBOMByScan, scanID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Type,
		&i.Engine,
		&i.Format,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one


SELECT id, name, target_key, description, created_at, updated_at FROM projects WHERE id = ?
`

// Vigila SQL queries (consumed by sqlc to generate type-safe Go code).
//
// Naming convention (sqlc):
//
//	:one   returns a single row
//	:many  returns multiple rows
//	:exec  no data returned
//
// Targets SQLite; keep ANSI-compatible for future PostgreSQL support.
// ============================================================================
// projects
// ============================================================================
func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByTargetKey = `-- name: GetProjectByTargetKey :one
SELECT id, name, target_key, description, created_at, updated_at FROM projects WHERE target_key = ?
`

func (q *Queries) GetProjectByTargetKey(ctx context.Context, targetKey string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByTargetKey, targetKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScan = `-- name: GetScan :one

SELECT id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at FROM scans WHERE id = ?
`

// ============================================================================
// scans
// ============================================================================
func (q *Queries) GetScan(ctx context.Context, id string) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.ScanType,
		&i.Profile,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerSource,
		&i.CreatedAt,
	)
	return i, err
}

const listEngineRunsByScan = `-- name: ListEngineRunsByScan :many
SELECT id, scan_id, engine, category, command, status, exit_code, duration_ms, raw_output_path, error_message, started_at, completed_at FROM engine_runs WHERE scan_id = ? ORDER BY started_at ASC
`

func (q *Queries) ListEngineRunsByScan(ctx context.Context, scanID string) ([]EngineRun, error) {
	rows, err := q.db.QueryContext(ctx, listEngineRunsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EngineRun
	for rows.Next() {
		var i EngineRun
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.Engine,
			&i.Category,
			&i.Command,
			&i.Status,
			&i.ExitCode,
			&i.DurationMs,
			&i.RawOutputPath,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByProject = `-- name: ListFindingsByProject :many
SELECT id, project_id, scan_id, engine_run_id, engine, category, rule_id, title, description, severity, cvss_score, cvss_vector, cwe, file_path, start_line, end_line, start_col, end_col, snippet, pkg_name, installed_version, fixed_version, secret_type, url, host, port, method, references_json, unique_id_from_tool, hash_code, status, created_at FROM findings WHERE project_id = ?
ORDER BY
  CASE severity
    WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2
    WHEN 'LOW' THEN 1 ELSE 0
  END DESC
LIMIT ? OFFSET ?
`

type ListFindingsByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListFindingsByProject(ctx context.Context, arg ListFindingsByProjectParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScanID,
			&i.EngineRunID,
			&i.Engine,
			&i.Category,
			&i.RuleID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwe,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.StartCol,
			&i.EndCol,
			&i.Snippet,
			&i.PkgName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.SecretType,
			&i.Url,
			&i.Host,
			&i.Port,
			&i.Method,
			&i.ReferencesJson,
			&i.UniqueIDFromTool,
			&i.HashCode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByScan = `-- name: ListFindingsByScan :many
SELECT id, project_id, scan_id, engine_run_id, engine, category, rule_id, title, description, severity, cvss_score, cvss_vector, cwe, file_path, start_line, end_line, start_col, end_col, snippet, pkg_name, installed_version, fixed_version, secret_type, url, host, port, method, references_json, unique_id_from_tool, hash_code, status, created_at FROM findings WHERE scan_id = ?
ORDER BY
  CASE severity
    WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2
    WHEN 'LOW' THEN 1 ELSE 0
  END DESC
`

func (q *Queries) ListFindingsByScan(ctx context.Context, scanID string) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScanID,
			&i.EngineRunID,
			&i.Engine,
			&i.Category,
			&i.RuleID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwe,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.StartCol,
			&i.EndCol,
			&i.Snippet,
			&i.PkgName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.SecretType,
			&i.Url,
			&i.Host,
			&i.Port,
			&i.Method,
			&i.ReferencesJson,
			&i.UniqueIDFromTool,
			&i.HashCode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByScanAssoc = `-- name: ListFindingsByScanAssoc :many
SELECT f.id, f.project_id, f.scan_id, f.engine_run_id, f.engine, f.category, f.rule_id, f.title, f.description, f.severity, f.cvss_score, f.cvss_vector, f.cwe, f.file_path, f.start_line, f.end_line, f.start_col, f.end_col, f.snippet, f.pkg_name, f.installed_version, f.fixed_version, f.secret_type, f.url, f.host, f.port, f.method, f.references_json, f.unique_id_from_tool, f.hash_code, f.status, f.created_at FROM scan_findings sf
JOIN findings f ON f.id = sf.finding_id
WHERE sf.scan_id = ?
ORDER BY
  CASE f.severity
    WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2
    WHEN 'LOW' THEN 1 ELSE 0
  END DESC
`

// findings actually observed by a scan, reconstructed via scan_findings.
// findings.scan_id migrates on later upserts, so a plain WHERE scan_id is wrong.
func (q *Queries) ListFindingsByScanAssoc(ctx context.Context, scanID string) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsByScanAssoc, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScanID,
			&i.EngineRunID,
			&i.Engine,
			&i.Category,
			&i.RuleID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwe,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.StartCol,
			&i.EndCol,
			&i.Snippet,
			&i.PkgName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.SecretType,
			&i.Url,
			&i.Host,
			&i.Port,
			&i.Method,
			&i.ReferencesJson,
			&i.UniqueIDFromTool,
			&i.HashCode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsOnlyInScan = `-- name: ListFindingsOnlyInScan :many
SELECT f.id, f.project_id, f.scan_id, f.engine_run_id, f.engine, f.category, f.rule_id, f.title, f.description, f.severity, f.cvss_score, f.cvss_vector, f.cwe, f.file_path, f.start_line, f.end_line, f.start_col, f.end_col, f.snippet, f.pkg_name, f.installed_version, f.fixed_version, f.secret_type, f.url, f.host, f.port, f.method, f.references_json, f.unique_id_from_tool, f.hash_code, f.status, f.created_at FROM scan_findings sf
JOIN findings f ON f.id = sf.finding_id
WHERE sf.scan_id = ?1 AND sf.hash_code NOT IN (
  SELECT other.hash_code FROM scan_findings other WHERE other.scan_id = ?2
)
ORDER BY
  CASE f.severity
    WHEN 'CRITICAL' THEN 4 WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2
    WHEN 'LOW' THEN 1 ELSE 0
  END DESC
`

type ListFindingsOnlyInScanParams struct {
	ScanID   string `json:"scan_id"`
	ScanID_2 string `json:"scan_id_2"`
}

// findings observed by scan ?1 but not by scan ?2, joined to current detail
func (q *Queries) ListFindingsOnlyInScan(ctx context.Context, arg ListFindingsOnlyInScanParams) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, listFindingsOnlyInScan, arg.ScanID, arg.ScanID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ScanID,
			&i.EngineRunID,
			&i.Engine,
			&i.Category,
			&i.RuleID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwe,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.StartCol,
			&i.EndCol,
			&i.Snippet,
			&i.PkgName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.SecretType,
			&i.Url,
			&i.Host,
			&i.Port,
			&i.Method,
			&i.ReferencesJson,
			&i.UniqueIDFromTool,
			&i.HashCode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectScansChronological = `-- name: ListProjectScansChronological :many
SELECT id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at FROM scans WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListProjectScansChronological(ctx context.Context, projectID string) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listProjectScansChronological, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Target,
			&i.ScanType,
			&i.Profile,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TriggerSource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, target_key, description, created_at, updated_at FROM projects ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListProjectsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetKey,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScans = `-- name: ListScans :many
SELECT id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at FROM scans ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListScansParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Target,
			&i.ScanType,
			&i.Profile,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TriggerSource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansByProject = `-- name: ListScansByProject :many
SELECT id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at FROM scans WHERE project_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListScansByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListScansByProject(ctx context.Context, arg ListScansByProjectParams) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScansByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Target,
			&i.ScanType,
			&i.Profile,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TriggerSource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapStaleRunningScans = `-- name: ReapStaleRunningScans :execrows
UPDATE scans
  SET status = 'failed', completed_at = CURRENT_TIMESTAMP
WHERE status = 'running' AND created_at < datetime('now', '-1 hour')
`

// mark scans left in 'running' by a dead process (killed / Ctrl-C) as failed.
// datetime('now', ...) yields the same text format as CURRENT_TIMESTAMP (SQLite).
func (q *Queries) ReapStaleRunningScans(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleRunningScans)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEngineRunStatus = `-- name: UpdateEngineRunStatus :one
UPDATE engine_runs
  SET status = ?,
      exit_code = ?,
      duration_ms = ?,
      error_message = ?,
      completed_at = ?
WHERE id = ?
RETURNING id, scan_id, engine, category, command, status, exit_code, duration_ms, raw_output_path, error_message, started_at, completed_at
`

type UpdateEngineRunStatusParams struct {
	Status       string     `json:"status"`
	ExitCode     *int64     `json:"exit_code"`
	DurationMs   *int64     `json:"duration_ms"`
	ErrorMessage *string    `json:"error_message"`
	CompletedAt  *time.Time `json:"completed_at"`
	ID           string     `json:"id"`
}

func (q *Queries) UpdateEngineRunStatus(ctx context.Context, arg UpdateEngineRunStatusParams) (EngineRun, error) {
	row := q.db.QueryRowContext(ctx, updateEngineRunStatus,
		arg.Status,
		arg.ExitCode,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.ID,
	)
	var i EngineRun
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Engine,
		&i.Category,
		&i.Command,
		&i.Status,
		&i.ExitCode,
		&i.DurationMs,
		&i.RawOutputPath,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateFindingStatus = `-- name: UpdateFindingStatus :one
UPDATE findings SET status = ? WHERE id = ? RETURNING id, project_id, scan_id, engine_run_id, engine, category, rule_id, title, description, severity, cvss_score, cvss_vector, cwe, file_path, start_line, end_line, start_col, end_col, snippet, pkg_name, installed_version, fixed_version, secret_type, url, host, port, method, references_json, unique_id_from_tool, hash_code, status, created_at
`

type UpdateFindingStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateFindingStatus(ctx context.Context, arg UpdateFindingStatusParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, updateFindingStatus, arg.Status, arg.ID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScanID,
		&i.EngineRunID,
		&i.Engine,
		&i.Category,
		&i.RuleID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwe,
		&i.FilePath,
		&i.StartLine,
		&i.EndLine,
		&i.StartCol,
		&i.EndCol,
		&i.Snippet,
		&i.PkgName,
		&i.InstalledVersion,
		&i.FixedVersion,
		&i.SecretType,
		&i.Url,
		&i.Host,
		&i.Port,
		&i.Method,
		&i.ReferencesJson,
		&i.UniqueIDFromTool,
		&i.HashCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateScanCreated = `-- name: UpdateScanCreated :one
UPDATE scans SET created_at = ? WHERE id = ? RETURNING id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at
`

type UpdateScanCreatedParams struct {
	CreatedAt time.Time `json:"created_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateScanCreated(ctx context.Context, arg UpdateScanCreatedParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, updateScanCreated, arg.CreatedAt, arg.ID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.ScanType,
		&i.Profile,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerSource,
		&i.CreatedAt,
	)
	return i, err
}

const updateScanStatus = `-- name: UpdateScanStatus :one
UPDATE scans
  SET status = ?,
      started_at = COALESCE(?, started_at),
      completed_at = COALESCE(?, completed_at)
WHERE id = ?
RETURNING id, project_id, target, scan_type, profile, status, started_at, completed_at, trigger_source, created_at
`

type UpdateScanStatusParams struct {
	Status      string     `json:"status"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
	ID          string     `json:"id"`
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, updateScanStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Target,
		&i.ScanType,
		&i.Profile,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TriggerSource,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFinding = `-- name: UpsertFinding :one
INSERT INTO findings (
  id, project_id, scan_id, engine_run_id, engine, category,
  rule_id, title, description, severity, cvss_score, cvss_vector, cwe,
  file_path, start_line, end_line, start_col, end_col, snippet,
  pkg_name, installed_version, fixed_version, secret_type,
  url, host, port, method,
  references_json,
  unique_id_from_tool, hash_code
) VALUES (
  ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?, ?, ?, ?,
  ?,
  ?, ?
)
ON CONFLICT(project_id, hash_code) DO UPDATE SET
  scan_id = excluded.scan_id,
  engine_run_id = excluded.engine_run_id,
  severity = excluded.severity,
  -- refresh descriptive fields from the latest scan; keep old value when the new one is NULL
  title = excluded.title,
  description = COALESCE(excluded.description, findings.description),
  cvss_score = COALESCE(excluded.cvss_score, findings.cvss_score),
  cvss_vector = COALESCE(excluded.cvss_vector, findings.cvss_vector),
  cwe = COALESCE(excluded.cwe, findings.cwe),
  fixed_version = COALESCE(excluded.fixed_version, findings.fixed_version),
  snippet = COALESCE(excluded.snippet, findings.snippet),
  references_json = COALESCE(excluded.references_json, findings.references_json),
  status = CASE WHEN findings.status = 'resolved' THEN 'open' ELSE findings.status END
RETURNING id, project_id, scan_id, engine_run_id, engine, category, rule_id, title, description, severity, cvss_score, cvss_vector, cwe, file_path, start_line, end_line, start_col, end_col, snippet, pkg_name, installed_version, fixed_version, secret_type, url, host, port, method, references_json, unique_id_from_tool, hash_code, status, created_at
`

type UpsertFindingParams struct {
	ID               string   `json:"id"`
	ProjectID        string   `json:"project_id"`
	ScanID           string   `json:"scan_id"`
	EngineRunID      string   `json:"engine_run_id"`
	Engine           string   `json:"engine"`
	Category         string   `json:"category"`
	RuleID           string   `json:"rule_id"`
	Title            string   `json:"title"`
	Description      *string  `json:"description"`
	Severity         string   `json:"severity"`
	CvssScore        *float64 `json:"cvss_score"`
	CvssVector       *string  `json:"cvss_vector"`
	Cwe              *string  `json:"cwe"`
	FilePath         *string  `json:"file_path"`
	StartLine        *int64   `json:"start_line"`
	EndLine          *int64   `json:"end_line"`
	StartCol         *int64   `json:"start_col"`
	EndCol           *int64   `json:"end_col"`
	Snippet          *string  `json:"snippet"`
	PkgName          *string  `json:"pkg_name"`
	InstalledVersion *string  `json:"installed_version"`
	FixedVersion     *string  `json:"fixed_version"`
	SecretType       *string  `json:"secret_type"`
	Url              *string  `json:"url"`
	Host             *string  `json:"host"`
	Port             *string  `json:"port"`
	Method           *string  `json:"method"`
	ReferencesJson   *string  `json:"references_json"`
	UniqueIDFromTool *string  `json:"unique_id_from_tool"`
	HashCode         string   `json:"hash_code"`
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, upsertFinding,
		arg.ID,
		arg.ProjectID,
		arg.ScanID,
		arg.EngineRunID,
		arg.Engine,
		arg.Category,
		arg.RuleID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.CvssScore,
		arg.CvssVector,
		arg.Cwe,
		arg.FilePath,
		arg.StartLine,
		arg.EndLine,
		arg.StartCol,
		arg.EndCol,
		arg.Snippet,
		arg.PkgName,
		arg.InstalledVersion,
		arg.FixedVersion,
		arg.SecretType,
		arg.Url,
		arg.Host,
		arg.Port,
		arg.Method,
		arg.ReferencesJson,
		arg.UniqueIDFromTool,
		arg.HashCode,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ScanID,
		&i.EngineRunID,
		&i.Engine,
		&i.Category,
		&i.RuleID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwe,
		&i.FilePath,
		&i.StartLine,
		&i.EndLine,
		&i.StartCol,
		&i.EndCol,
		&i.Snippet,
		&i.PkgName,
		&i.InstalledVersion,
		&i.FixedVersion,
		&i.SecretType,
		&i.Url,
		&i.Host,
		&i.Port,
		&i.Method,
		&i.ReferencesJson,
		&i.UniqueIDFromTool,
		&i.HashCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, name, target_key, description) VALUES (?, ?, ?, ?)
  ON CONFLICT(target_key) DO UPDATE SET name = excluded.name, updated_at = CURRENT_TIMESTAMP
  RETURNING id, name, target_key, description, created_at, updated_at
`

type UpsertProjectParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	TargetKey   string  `json:"target_key"`
	Description *string `json:"description"`
}

// Upsert keyed by target_key (identity); name is a mutable display label.
// Re-scanning the same target maps to the same project row.
func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject,
		arg.ID,
		arg.Name,
		arg.TargetKey,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetKey,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
